name: Environment Demo

on:
  workflow_dispatch:

jobs:
  show-staging:
    runs-on: ubuntu-latest
    environment: staging
    env:
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

    steps:
      - name: Show github deployment environment
        run: 'echo "Environment: ${{ vars.APP_ENV }}"'

      - name: Show URL
        run: 'echo "URL: ${{ vars.DEPLOY_URL }}"'

      - name: Show deploy token
        run: |
          if [ -n "$DEPLOY_TOKEN" ]; then
            echo "Deploy token is available"
          fi

  show-production:
    runs-on: ubuntu-latest
    environment: production
    env:
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

    steps:
      - name: Show github deployment environment
        run: 'echo "Environment: ${{ vars.APP_ENV }}"'

      - name: Show URL
        run: 'echo "URL: ${{ vars.DEPLOY_URL }}"'

      - name: Show deploy token
        run: |
          if [ -n "$DEPLOY_TOKEN" ]; then
            echo "Deploy token is available"
          fi
