name: Hello Github Actions

on:
  push:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print greeting
        run: echo "Hello from Github Actions"

      - name: Show current user
        run: whoami

      - name: Show operating system
        run: uname -a

      - name: Show working directory
        run: pwd

      - name: List files
        run: ls -al
