name: Hello Github Actions

on:
  push:

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current directory
        run: pwd

      - name: List repository files
        run: ls -al

      - name: Read README
        run: cat README.md
